version: '3.8'
services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: jose_aula
      POSTGRES_USER: jose123
      POSTGRES_PASSWORD: 123456
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: